"""empty message

Revision ID: 0130596ee11f
Revises: 
Create Date: 2022-03-18 22:07:49.662567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0130596ee11f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propertyTitle', sa.String(length=80), nullable=True),
    sa.Column('no_of_bedrooms', sa.Integer(), nullable=True),
    sa.Column('no_of_bathrooms', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('propertyType', sa.String(length=80), nullable=True),
    sa.Column('propertyDesc', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
