"""empty message

Revision ID: 09f2d3192bf9
Revises: 
Create Date: 2022-03-20 12:09:54.542331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f2d3192bf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('propertyTitle', sa.String(length=255), nullable=True),
    sa.Column('propertyDesc', sa.String(length=500), nullable=True),
    sa.Column('no_of_bedrooms', sa.Integer(), nullable=True),
    sa.Column('no_of_bathrooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('propertyType', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
